export const loginActionType = {
    LOGIN_SUBMIT: 'LOGIN_SUBMIT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT_SUBMIT: 'LOGOUT_SUBMIT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
};

export const accountActionType = {
    GET_LIST_ACCOUNT: 'GET_LIST_ACCOUNT',
    GET_LIST_ACCOUNT_SUCCESS: 'GET_LIST_ACCOUNT_SUCCESS',
    GET_LIST_ACCOUNT_FAILED: 'GET_LIST_ACCOUNT_FAILED',
    ADD_ACCOUNT: 'ADD_ACCOUNT',
    ADD_ACCOUNT_SUCCESS: 'ADD_ACCOUNT_SUCCESS',
    ADD_ACCOUNT_FAILED: 'ADD_ACCOUNT_FAILED',
    DETAIL_ACCOUNT: 'DETAIL_ACCOUNT',
    DETAIL_ACCOUNT_SUCCESS: 'DETAIL_ACCOUNT_SUCCESS',
    DETAIL_ACCOUNT_FAILED: 'DETAIL_ACCOUNT_FAILED',
    UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
    UPDATE_ACCOUNT_SUCCESS: 'UPDATE_ACCOUNT_SUCCESS',
    UPDATE_ACCOUNT_FAILED: 'UPDATE_ACCOUNT_FAILED',
    DELETE_ACCOUNT: 'DELETE_ACCOUNT',
    DELETE_ACCOUNT_SUCCESS: 'DELETE_ACCOUNT_SUCCESS',
    DELETE_ACCOUNT_FAILED: 'DELETE_ACCOUNT_FAILED',
};

export const freelancerActionType = {
    GET_LIST_FREELANCER: 'GET_LIST_FREELANCER',
    GET_LIST_FREELANCER_SUCCESS: 'GET_LIST_FREELANCER_SUCCESS',
    GET_LIST_FREELANCER_FAILED: 'GET_LIST_FREELANCER_FAILED',
    ADD_FREELANCER: 'ADD_FREELANCER',
    ADD_FREELANCER_SUCCESS: 'ADD_FREELANCER_SUCCESS',
    ADD_FREELANCER_FAILED: 'ADD_FREELANCER_FAILED',
    DETAIL_FREELANCER: 'DETAIL_FREELANCER',
    DETAIL_FREELANCER_SUCCESS: 'DETAIL_FREELANCER_SUCCESS',
    DETAIL_FREELANCER_FAILED: 'DETAIL_FREELANCER_FAILED',
    UPDATE_FREELANCER: 'UPDATE_FREELANCER',
    UPDATE_FREELANCER_SUCCESS: 'UPDATE_FREELANCER_SUCCESS',
    UPDATE_FREELANCER_FAILED: 'UPDATE_FREELANCER_FAILED',
    DELETE_FREELANCER: 'DELETE_FREELANCER',
    DELETE_FREELANCER_SUCCESS: 'DELETE_FREELANCER_SUCCESS',
    DELETE_FREELANCER_FAILED: 'DELETE_FREELANCER_FAILED',
};

export const jobActionType = {
    GET_LIST_JOB: 'GET_LIST_JOB',
    GET_LIST_JOB_SUCCESS: 'GET_LIST_JOB_SUCCESS',
    GET_LIST_JOB_FAILED: 'GET_LIST_JOB_FAILED',
    ADD_JOB: 'ADD_JOB',
    ADD_JOB_SUCCESS: 'ADD_JOB_SUCCESS',
    ADD_JOB_FAILED: 'ADD_JOB_FAILED',
    DETAIL_JOB: 'DETAIL_JOB',
    DETAIL_JOB_SUCCESS: 'DETAIL_JOB_SUCCESS',
    DETAIL_JOB_FAILED: 'DETAIL_JOB_FAILED',
    UPDATE_JOB: 'UPDATE_JOB',
    UPDATE_JOB_SUCCESS: 'UPDATE_JOB_SUCCESS',
    UPDATE_JOB_FAILED: 'UPDATE_JOB_FAILED',
    DELETE_JOB: 'DELETE_JOB',
    DELETE_JOB_SUCCESS: 'DELETE_JOB_SUCCESS',
    DELETE_JOB_FAILED: 'DELETE_JOB_FAILED',
};

export const transactionActionType = {
    GET_LIST_TRANSACTION: 'GET_LIST_TRANSACTION',
    GET_LIST_TRANSACTION_SUCCESS: 'GET_LIST_TRANSACTION_SUCCESS',
    GET_LIST_TRANSACTION_FAILED: 'GET_LIST_TRANSACTION_FAILED',
};

export const statisticActionType = {
    GET_STATISTIC_ACCOUNT: 'GET_STATISTIC_ACCOUNT',
    GET_STATISTIC_ACCOUNT_SUCCESS: 'GET_STATISTIC_ACCOUNT_SUCCESS',
    GET_STATISTIC_ACCOUNT_FAILED: 'GET_STATISTIC_ACCOUNT_FAILED',
    GET_STATISTIC_JOB: 'GET_STATISTIC_JOB',
    GET_STATISTIC_JOB_SUCCESS: 'GET_STATISTIC_JOB_SUCCESS',
    GET_STATISTIC_JOB_FAILED: 'GET_STATISTIC_JOB_FAILED',
    GET_STATISTIC_FINANCIAL: 'GET_STATISTIC_FINANCIAL',
    GET_STATISTIC_FINANCIAL_SUCCESS: 'GET_STATISTIC_FINANCIAL_SUCCESS',
    GET_STATISTIC_FINANCIAL_FAILED: 'GET_STATISTIC_FINANCIAL_FAILED',
};

export const userActionType = {
    GET_USER_INFO: 'GET_USER_INFO',
    GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
    GET_USER_INFO_FAILED: 'GET_USER_INFO_FAILED',
};
